# Generated by Django 4.1.3 on 2022-12-21 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BalancingProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.CharField(max_length=255, verbose_name='Описание')),
                ('price', models.CharField(max_length=255, verbose_name='Стоимость')),
                ('images', models.FileField(upload_to='images/')),
            ],
            options={
                'verbose_name': 'Балансировка',
                'verbose_name_plural': 'Балансировка',
            },
        ),
        migrations.CreateModel(
            name='BalancingProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images', models.FileField(upload_to='images/')),
                ('post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='Balancing.balancingproduct')),
            ],
        ),
    ]
