# Generated by Django 4.1.3 on 2022-12-23 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Balancing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='balancingproduct',
            options={'verbose_name': 'Балансировка и ремонт барабанов', 'verbose_name_plural': 'Балансировка и ремонт барабанов'},
        ),
        migrations.AddField(
            model_name='balancingproduct',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='images/', verbose_name='Видео(необязательно)'),
        ),
    ]
